CREATE TABLE [dbo].[MonitoringQueryLog]
(
    [Id]                        BIGINT IDENTITY(1,1)     NOT NULL,
    [CompanyFk]                 BIGINT                   NOT NULL,
    [JobFk]                     BIGINT                   NOT NULL,
    [DatabaseName]              NVARCHAR(128)            NOT NULL,
    [WaitType]                  NVARCHAR(128)            NOT NULL DEFAULT 'cpu',
    [TopNo]                     INT                      NOT NULL DEFAULT 1,
    [QueryPlanCost]             FLOAT                    NULL,
    [QueryText]                 NVARCHAR(MAX)            NULL,
    [Warnings]                  VARCHAR(MAX)             NULL,
    [QueryPlan]                 XML                      NULL,
    [MissingIndexes]            NVARCHAR(MAX)            NULL,
    [ImplicitConversionInfo]    NVARCHAR(MAX)            NULL,
    [ExecutionCount]            BIGINT                   NULL,
    [ExecutionsPerMinute]       MONEY                    NULL,
    [TotalCpu]                  BIGINT                   NULL,
    [AverageCpu]                BIGINT                   NULL,
    [TotalDuration]             BIGINT                   NULL,
    [AverageDuration]           BIGINT                   NULL,
    [TotalReads]                BIGINT                   NULL,
    [AverageReads]              BIGINT                   NULL,
    [TotalReturnedRows]         BIGINT                   NULL,
    [AverageReturnedRows]       MONEY                    NULL,
    [MinReturnedRows]           BIGINT                   NULL,
    [MaxReturnedRows]           BIGINT                   NULL,
    [NumberOfPlans]             INT                      NULL,
    [NumberOfDistinctPlans]     INT                      NULL,
    [LastExecutionTime]         DATETIME                 NULL,
    [QueryHash]                 BINARY(8)                NULL,
    CONSTRAINT [PK_MonitoringQueryLog] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MonitoringQueryLog_JobExecution] FOREIGN KEY ([JobFk]) REFERENCES [dbo].[JobExecution]([Id]),
    CONSTRAINT [FK_MonitoringQueryLog_Company] FOREIGN KEY ([CompanyFk]) REFERENCES [dbo].[Company]([Id])
);
