CREATE TABLE [dbo].[Company]
(
	[Id]					BIGINT				IDENTITY (1, 1) NOT NULL,
	[Name]					NVARCHAR(64)		NOT NULL,
	[ApiKey]				UNIQUEIDENTIFIER	NOT NULL,
	[DoMaintenancePeriod]	SMALLINT			NOT NULL DEFAULT 1,
	[DoMonitoringPeriod]	SMALLINT			NOT NULL DEFAULT 0,
	CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
)
