name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build ${{ matrix.packageName }}
      run: dotnet build src/${{ matrix.packageName }}/${{ matrix.packageName }}.csproj --configuration Release

    - name: Package ${{ matrix.packageName }}
      run: |
        buildNumber=${{ github.run_number }}
        packageVersion="1.0.$buildNumber"
        dotnet pack src/${{ matrix.packageName }}/${{ matrix.packageName }}.csproj --version-suffix $packageVersion --configuration Release

    - name: Publish NuGet ${{ matrix.packageName }}
      run: dotnet nuget push src/${{ matrix.packageName }}/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_PUBLISH_API_KEY }}" --source https://api.nuget.org/v3/index.json
