name: Publish NuGet Package SqlSensei.Core

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build SqlSensei.Core
      run: dotnet build src/SqlSensei.Core/SqlSensei.Core.csproj --configuration Release

    - name: Package SqlSensei.Core
      run: |
        dotnet pack src/SqlSensei.Core/SqlSensei.Core.csproj -p:Version="1.0.1" --configuration Release

    - name: Publish NuGet SqlSensei.Core
      run: dotnet nuget push src/SqlSensei.Core/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_PUBLISH_API_KEY }}" --source https://api.nuget.org/v3/index.json
