name: Publish NuGet SqlSensei.SqlServer
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        packageName: ['SqlSensei.SqlServer']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Common Steps
      uses: ./.github/workflows/release-nuget.yml
