name: Publish NuGet SqlSensei.SqlServer.EndpointLogger
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        packageName: ['SqlSensei.SqlServer.EndpointLogger']
    runs-on: ubuntu-latest
    steps:
    - name: Common Steps
      uses: ./.github/workflows/release-nuget.yml
