name: Publish NuGet SqlSensei.SqlServer.Hangfire

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build SqlSensei.SqlServer.Hangfire
      run: dotnet build src/SqlSensei.SqlServer.Hangfire/SqlSensei.SqlServer.Hangfire.csproj --configuration Release
        
    - name: Package SqlSensei.SqlServer.Hangfire
      run: dotnet pack src/SqlSensei.SqlServer.Hangfire/SqlSensei.SqlServer.Hangfire.csproj --configuration Release

    - name: Setup API_KEY NuGet SqlSensei.SqlServer.Hangfire
      run: nuget setapikey "${{ secrets.NUGET_PUBLISH_API_KEY }}" -source https://api.nuget.org/v3/index.json

    - name: Publish NuGet SqlSensei.SqlServer.Hangfire
      run: dotnet nuget push src/SqlSensei.SqlServer.Hangfire/bin/Release/*.nupkg  --source https://api.nuget.org/v3/index.json
