name: Publish NuGet Package SqlSensei.SqlServer.EndpointLogger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Build SqlSensei.SqlServer.EndpointLogger
      run: dotnet build src/SqlSensei.SqlServer.EndpointLogger/SqlSensei.SqlServer.EndpointLogger.csproj --configuration Release

    - name: Package SqlSensei.SqlServer.EndpointLogger
      run: |
        buildNumber=${{ github.run_number }}
        packageVersion="1.0.$buildNumber"
        dotnet pack src/SqlSensei.SqlServer.EndpointLogger/SqlSensei.SqlServer.EndpointLogger.csproj -p:Version=$packageVersion --configuration Release

    - name: Publish NuGet SqlSensei.SqlServer.EndpointLogger
      run: dotnet nuget push src/SqlSensei.SqlServer.EndpointLogger/bin/Release/*.nupkg --api-key "${{ secrets.NUGET_PUBLISH_API_KEY }}" --source https://api.nuget.org/v3/index.json
