name: Publish NuGet SqlSensei.SqlServer.Hangfire
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        packageName: ['SqlSensei.SqlServer.Hangfire']
    runs-on: ubuntu-latest
    steps:
    - name: Common Steps
      uses: ./.github/workflows/nuget-publish-template.yml
